on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/cargo-build-publish.yml@cb078a50f0101bc0c1fcd4077d3193a1cc655bf4 # main
    secrets:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
