on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/cargo-build-publish.yml@3ecb538763d2fffc0d19a5962a2ac4cd9eda0063 # main
    with:
      publish: false
