on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/cargo-build-publish.yml@1d5fd10ef9389b5c7c34ffa80d0f220b48b65181 # main
    with:
      publish: false
